# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6458a3ff80854e9ad09ec49610072fc737c7e8d8472e37f0645824c632153a70cb7826139685cd2e50811bcd08173f2c46018d264f2af4c913ea2c846ca92507
  rachio_auth_token: <%= ENV["RACHIO_AUTH_TOKEN"] %>

test:
  secret_key_base: 1caeb2b8dccc0494dd8abe22154389978b7c85a4f2af7c5e46e58b7e92f60bee60878e481846d406beaeb0e4ef63d759cd274bb42491a5d2ef054108c99bda22
  rachio_auth_token: <%= ENV["RACHIO_AUTH_TOKEN"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rachio_auth_token: <%= ENV["RACHIO_AUTH_TOKEN"] %>
